### ISSUE TITLE
Translations flags

### ISSUE THREAD

**Issue by nicolas-bastien** [ezsystems/ezplatform-i18n#23]
![crowdin](https://cloud.githubusercontent.com/assets/1446466/22544572/a69b4594-e935-11e6-9018-a249cdbbc570.png)

This issue allow us to store every flags for documentation.

![de](https://cloud.githubusercontent.com/assets/1446466/22544452/1909fbf8-e935-11e6-9cbe-2f40406eb22b.png)
![es-es](https://cloud.githubusercontent.com/assets/1446466/22544453/190c6f78-e935-11e6-8a09-94cd71544192.png)
![fi](https://cloud.githubusercontent.com/assets/1446466/22544454/1911badc-e935-11e6-8164-08cdad424e7e.png)
![fr](https://cloud.githubusercontent.com/assets/1446466/22544456/191490fe-e935-11e6-9e6b-88e2ff4ed48e.png)
![hi](https://cloud.githubusercontent.com/assets/1446466/22544455/1912ac80-e935-11e6-89e7-f11a25adbf1a.png)
![hu](https://cloud.githubusercontent.com/assets/1446466/22544457/1916e8d6-e935-11e6-9ea8-c75678bd0a6f.png)
![ja](https://cloud.githubusercontent.com/assets/1446466/22544461/1948b64a-e935-11e6-9eee-51c8e452b9fb.png)
![nb](https://cloud.githubusercontent.com/assets/1446466/22544462/194b441e-e935-11e6-9f83-5eac2fa67214.png)
![pl](https://cloud.githubusercontent.com/assets/1446466/22544463/19511376-e935-11e6-9555-c812a2c1e783.png)
![pt-pt](https://cloud.githubusercontent.com/assets/1446466/22544459/193ffc6c-e935-11e6-94a3-258cd1a87e51.png)
![ru](https://cloud.githubusercontent.com/assets/1446466/22544460/19422906-e935-11e6-809f-c060ad57f2a8.png)

**Comment by bdunogier** [comment]
I think we can close it, the images will remain, and we can till edit it.
